### ISSUE TITLE
[Fullstack] Update Profile Picture Components in Web App

### ISSUE THREAD

**Issue by johannesq23** [GTBitsOfGood/brain-exercise-analytics#116]
## Context

We want to make some changes with the profile pictures and add some functionality as well. We want to change the image in the profile modal to be circular, ensure that one singular default image is used throughout, and display the profile images in the expanded row of volunteer search.

## Requirements

Default images for the Profile Modal & navigation panel (the bottom left corner) needs to be updated to match the one [in Figma](https://www.figma.com/design/hPK3RX40paMClQQPhJB5lR/Brain-Exercise-Initiative-SPRING24-new?node-id=4065-31620&t=IGeoAh9axYj7gFhx-0) (Figma has two different images for the two. Use the one that is actually shown in the modal)
Look at `src/components/AccountEditModal` and `src/components/NavigationPanel` to implement the changes. Try uploading an image on your account and test that it works.

The Image in Profile Modal needs to be circular. Change that in `src/components/AccountEditModal/Profile.tsx`

Also, images should be displayed in expanded row of volunteer search. Right now they are being defaulted to a default profile image. Look at `src/components/VolunteerGrid/Row` and `src/components/VolunteerApprovalGrid/Row` to see where you need to put the profile pictures. 

## Acceptance Criteria

- [x] Default Images are now constant throughout the whole app
- [x] Testing is done to ensure that profile pictures can be uploaded
- [x] Image in profile Modal is now circular
- [x] Image is displayed in the expanded row of volunteer search

**Comment by ND68** [comment]
Fixed default icon. Updated conditional pfp locations on sidebar, edit profile modal, and volunteer extended rows. Reformated areas affected. Tested uploading profile pictures: although it works, it takes a bit of time for the page to reflect the changes; admins will be able to view volunteer profile pictures if they have one.

**Comment by ND68** [comment]
Fixed default icon. Updated conditional pfp locations on sidebar, edit profile modal, and volunteer extended rows. Reformated areas affected. Tested uploading profile pictures: although it works, it takes a bit of time for the page to reflect the changes; admins will be able to view volunteer profile pictures if they have one.
