### ISSUE TITLE
[Fullstack] Sprint Day Tasks 2

### ISSUE THREAD

**Issue by johannesq23** [GTBitsOfGood/brain-exercise-analytics#145]
## Requirements

- Work on Hover States and tooltips with yixiao. [link](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02?p=133bd5d1ba1580f28f0ae0d74a1aac6a&pm=s) 
- Work on the Analytics screen [link1](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02?p=133bd5d1ba158087b294fe1a46b0080e&pm=s) [link2](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02)
- Selected group a list instead of dropdown [link](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02?p=133bd5d1ba158079b10bc08ae472876c&pm=s)
- add x to modals [link](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02?p=133bd5d1ba1580cfa3cde2603a48a844&pm=s)
- Do not inform if email/pass is wrong, also, when email pending, don't show this message. [link](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02?p=133bd5d1ba1580b48ac1d4a4e12ecf5f&pm=s)
- Look into why you cannot log in with different email after change [link](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02?p=133bd5d1ba1580d5a196c00747651a6a&pm=s)
- Look into this- I wasn't able to reproduce/understand here. [link](https://www.notion.so/gtbitsofgood/Sprint-Day-122bd5d1ba1580338cfded14c7341a02?p=133bd5d1ba1580208770d15ab3cc91cc&pm=s)

## Acceptance Criteria

- [ ] Criteria

**Comment by yixiaosz** [comment]
## Hover state clarifications

- Unless stated, **the clips below are all from Figma** and are the hover states that are currently missing from the built website. 

- Color guide: Use the chart below to link the verbal color names to their hex numbers. 
<img width="833" alt="Screenshot 2024-11-03 at 11 21 34" src="https://github.com/user-attachments/assets/9f0cd63f-2a97-4d8d-980e-4a3c875eaadc">

### 1. [Side Bar](https://www.figma.com/design/DsK6uATSqnLdCW6zTM1Qdr/Brain-Exercise-Initiative-FALL24?node-id=8658-125475&t=heVlrBysE6Eb5eYn-1)
- Buttons that have dark blue text turns light blue [link](https://www.figma.com/design/DsK6uATSqnLdCW6zTM1Qdr/Brain-Exercise-Initiative-FALL24?node-id=4440-37523&t=heVlrBysE6Eb5eYn-1)
![hover3](https://github.com/user-attachments/assets/a4776936-6683-41df-9ead-a9a94a156bc5)
- Profile button [link](https://www.figma.com/design/DsK6uATSqnLdCW6zTM1Qdr/Brain-Exercise-Initiative-FALL24?node-id=4382-31127&t=heVlrBysE6Eb5eYn-1)
![hover4-2](https://github.com/user-attachments/assets/0eb3addc-30c3-4926-9f57-8f3044919c91)

**Comment by yixiaosz** [comment]
### 2. Advanced Search 
- While the default color for each button is light blue grey, it turns to white while hovering. Selected buttons doesn't have any color change while hovering (please note that for buttons that have dropdown function, the little arrow/triangle will turn light blue while hovering <- not implemented, a little annoying. will come back to it - soph) 
- Use this [link](https://www.figma.com/design/DsK6uATSqnLdCW6zTM1Qdr/Brain-Exercise-Initiative-FALL24?node-id=4393-32613&t=heVlrBysE6Eb5eYn-1) to see how each button looks at different states. 
![hover5](https://github.com/user-attachments/assets/a1c46e8b-b7b4-45f4-872e-52ae80e657de)
![hover1](https://github.com/user-attachments/assets/ca240ed1-d8f8-495f-88f3-cc4be3f32a79)

**Comment by yixiaosz** [comment]
### 3. Volunteer list
- (Applies to patient list too) Dropdown arrow is too small in the built website, make it the same height (retain original aspect ratio) as the text on its right. 
<img width="106" alt="Screenshot 2024-11-03 at 12 55 58" src="https://github.com/user-attachments/assets/5aa88cab-a54d-4deb-8de8-cd35601aa6c1">

- (Applies to patient list too) Currently only clicking the arrow opens the dropdown, make both the name and the arrow clickable. (Is it hard to apply this expanding animation? If takes a long time, just skip it)
![hover8](https://github.com/user-attachments/assets/d3c8010e-d92d-48ef-8a3e-4396d8e28442)


- **Delete account** and **Remove from Chapter** buttons drop 50% opacity while hovering
![hover6](https://github.com/user-attachments/assets/69113253-80c0-4445-a235-b190311a239d)
![hover7](https://github.com/user-attachments/assets/39998a30-f938-4483-9d1d-6a844191dc03)

- Delete account modal (details in [figma](https://www.figma.com/design/DsK6uATSqnLdCW6zTM1Qdr/Brain-Exercise-Initiative-FALL24?node-id=4111-50501&t=heVlrBysE6Eb5eYn-1)): opacity drops 50%
![hover11](https://github.com/user-attachments/assets/5a22d59d-1a75-4b5c-bd0d-1fc1ec0385f7)

- same thing for leadership transfer second confirmation modal (similar tasks followed in 5. hover buttons)
<img width="623" alt="Screenshot 2024-11-03 at 15 21 24" src="https://github.com/user-attachments/assets/2ea7e772-8fbd-4b28-a9ea-1780ed5f0e00">

**Comment by yixiaosz** [comment]
### 4. My Chapter page
- Hover state added for chapter management buttons (instant color changes), chapter profile remains still bc they're not clickable. Refer to the [figma design](https://www.figma.com/design/DsK6uATSqnLdCW6zTM1Qdr/Brain-Exercise-Initiative-FALL24?node-id=8444-44212&t=heVlrBysE6Eb5eYn-1) for details. Please note that delete chapter has red hove r text color
- Please help me confirm if this is implemented: 'delete chapter' button is exclusively for director and national/regional exec., not visible for chapter presidents
![hover9](https://github.com/user-attachments/assets/24ef9df3-91e4-46f9-9336-f429de2cd2e6)
- Leadership transfer text input boxes has this new hover style defined. (**also applies to all text input boxes, I will provide a list of locations in the next post**)
<img width="774" alt="textinput guide" src="https://github.com/user-attachments/assets/d3426d4d-542b-48e8-a6e4-461b57d56241">

(I only made this first name box hovering state, but apply the same style to the rest two boxes. 
![hover10](https://github.com/user-attachments/assets/02c66b44-ecd6-471e-b08f-b837da88a11d)

**Comment by yixiaosz** [comment]
### List of Text input boxes that will need style update: 
1. My Chapter/leadership transfer
2. My Chapter/Edit chapter profile (**Attention**: text in box is existing info so should use dark blue)
3. My Chapter/Add volunteer
4. Search Chapter/Add new chapter
5. Edit user profile/profile (**Attention**: currently it's using user's system focus color, make it fixed to black)
<img width="525" alt="Screenshot 2024-11-03 at 15 31 00" src="https://github.com/user-attachments/assets/aceaad37-e960-4d95-bb8a-ed1147463239">

7. Edit user profile/change password
8. Search bars at Search Chapter, Search Volunteer, Search Patient, My Chapter's Search volunteer (**Attention**: No black strokes needed during editing. currently we have the black strokes so need to remove it)

**Comment by yixiaosz** [comment]
### 5. button hover state
<img width="828" alt="button guide" src="https://github.com/user-attachments/assets/16696404-8568-4287-9efd-02d95a9d459d">

### This style change applies to the following locations: 
1. Patient list: view analytics, view group analytics buttons
2. Volunteer list/change access level: apply role button
3. Volunteer list/change status: apply status button
4. volunteer list/delete account: delete and cancel button
5. pending approval: approve and deny button
6. Search Chapter: add chapter, view profile button
7. Search Chapter/add new chapter: (**First, change 'discard' to 'cancel'**) cancel and confirm button
8. My Chapter/edit chapter profile: (**First, change 'discard' to 'cancel'**) cancel and confirm button
9. My Chapter/leadership transfer: (**First, change all 'chapter transfer' text to 'leadership transfer'**) cancel and confirm button
10. My Chapter/add volunteer: (**First, change 'discard' to 'cancel'**) cancel and confirm button
11. My Chapter/delete chapter: cancel and delete button
12. Search bar/advanced search (search patient, search volunteer): clear and confirm button

**Comment by yixiaosz** [comment]
## Popups after an action
I created this [template](https://www.figma.com/design/DsK6uATSqnLdCW6zTM1Qdr/Brain-Exercise-Initiative-FALL24?node-id=10003-57255&t=qIsmwj8OkUjtZYth-1) for all kind of confirmation popups, whether it's after adding volunteer or after remove one from a chapter. 
<img width="648" alt="Screenshot 2024-11-05 at 13 07 12" src="https://github.com/user-attachments/assets/26fc4745-f000-457b-bf7f-7d7f2c3fdfe0">
<img width="705" alt="Screenshot 2024-11-05 at 13 07 22" src="https://github.com/user-attachments/assets/f529b857-0d28-4227-b3f9-fdb33114f6e4">
<img width="700" alt="Screenshot 2024-11-05 at 13 08 47" src="https://github.com/user-attachments/assets/d0a089d6-4527-4a89-852c-280ce98cf11a">
