### ISSUE TITLE
[Frontend] Implement Analytics Graphs and Components

### ISSUE THREAD

**Issue by samarth52** [GTBitsOfGood/brain-exercise-analytics#24]
## Context

During these past two Sprints, we worked on collecting analytics data about the progress of patients using the BEI app. We now want to create nice visualizations for these data for BEI's volunteers and admins, so they can get insights on how patients are doing. These visualizations will be displayed in the analytics dashboard.

## Requirements

We want to create reusable graphs and components that suit the needs of a wide array of data. Utilize [d3.js](https://d3js.org/) or any suitable graph library to create the graph below.

## Line Chart

![image](https://github.com/GTBitsOfGood/brain-exercise-analytics/assets/57265280/5c4ce34d-10cf-4c4d-b478-f28c08674c88)

Figma: https://www.figma.com/file/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=841-6518&mode=design&t=iTsHWnRy9swPSTtB-0

**Note: Do not implement the calendar button in the top right corner since we are still discussing its usage and user flow**

This component will accept data in the format:
```
data: [
  {
    interval: string;
    value: number;
  }
]
```

Generate the x-axis from the `interval` field of `data` elements.

For the y-axis, the component will accept the optional prop:
```
yAxis?: {
  min: number,
  max: number,
  numDivisions: num,
  format?: (number): string,
}
```

- If this prop is `undefined`, autoscale the y-axis based on the input data
- Else, create a fixed scale based on the config. The optional format function will be used to format the number shown at each division (eg: if we want to show percentages). If this function is not provided, default to displaying the number as it is.

This component should also accept an optional `gradient: boolean` prop:
- If this is set, a gradient below the line graph will be displayed as seen in this Figma link: https://www.figma.com/file/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=964-6241&mode=design&t=5PClNStPvG3xYp3Y-0

Miscellaneous props:
- `title`: The title of the graph displayed in the top left corner
- `width`: Controls the width of the component
- `height`: Controls the height of the component
- `hoverable`: Optional boolean value that controls whether you can hover over the graph to see the actual value for a given week
- `percentageChange`: Optional boolean value. If this is set, the uptick/downtick in the Figma design will be displayed depending on whether the value is negative or positive

Make sure this line graph is smooth.

## Bar Chart

![image](https://github.com/GTBitsOfGood/brain-exercise-analytics/assets/57265280/bf670db8-d4bb-4f0d-b0ee-8ff431565c58)

Figma: https://www.figma.com/file/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=841-6518&mode=design&t=iTsHWnRy9swPSTtB-0

**Note: Do not implement the calendar button in the top right corner since we are still discussing its usage and user flow**

This component takes in the same props as the Line Chart component

Extra Miscellaneous props (apart from those of Line Chart):
- `highlightLargest`: Changes the color of the largest bar to #FF9FB3. For example:

![image](https://github.com/GTBitsOfGood/brain-exercise-analytics/assets/57265280/669321a0-a7b3-4ab7-888d-a3dfc3f1367d)

## Stacked Bar Chart

![image](https://github.com/GTBitsOfGood/brain-exercise-analytics/assets/57265280/f5c4e309-8472-4d35-965f-6c5fc19ddfa9)

Figma Link: https://www.figma.com/file/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=841-6686&mode=design&t=Rr55UlTPtFVPiyT6-0

This component takes in the same props as the Line Chart component, with the only difference being in the `data` prop:
```
data: [
  {
    interval: string;
    value: number;
    stackedValue: number;
  }
]
```

The blue portion is equal to `smallerValue`, and pink portion is equal to `stackedValue`

Reuse components and functions wherever possible, such as a function to generate all Monday dates in a given range.

## Small Data Box

![image](https://github.com/GTBitsOfGood/brain-exercise-analytics/assets/57265280/017861cd-90c0-46f4-8756-9d23f417430a)

Figma Link: https://www.figma.com/file/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=941-6334&mode=design&t=Rr55UlTPtFVPiyT6-0

It should accept props for `title: string`, `icon`, and `text: string` (text is like "20 / 1 hr 50 min").
It should also accept optional `height` and `width` props, with the default values being that in the Figma design

## Acceptance Criteria

- [x] Create Line Chart component
- [x] Create Bar Chart component
- [x] Create Stacked Bar Chart component
- [x] Create Small Data Box component

**Comment by thanasis457** [comment]
The shade underneath the line graph is a bit tricky to get. I will attempt to add it tonight. The rest is working though.
