### ISSUE TITLE
[Frontend] Create Overall Analytic Dashboard Section

### ISSUE THREAD

**Issue by samarth52** [GTBitsOfGood/brain-exercise-analytics#35]
## Context

Now that we are able to collect all analytics data from the BEI Mobile App, we want to create the dashboard so that BEI admins and volunteers can view the patient data. This ticket focuses on creating components for sections in the dashboard to view global analytics as well as an overview of some patient-specific analytics.

## Requirements

The graph components have already been implemented. Their usage can be found in the corresponding [ticket](https://github.com/GTBitsOfGood/brain-exercise-analytics/issues/24). You can also view the `/src/app/page.tsx` file for some example graphs, which can be viewed on `localhost:3000/`.

For all designs, view the following Figma link:
https://www.figma.com/file/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=1598-13219&mode=design&t=sk6OdQB0VhMJHzgn-0

Create the following sections as two different components and use dummy data for the graphs. Create appropriate sub-components for graphs or items that don't exist, such as the streak.

For the streak component specifically, it should take in a `days: Days[]` prop (Days is defined in `common_utils/types.ts`). A circle is filled with blue and gets a checkmark only if the corresponding day is present in the `days` array. The line between two circles is filled with blue only if the two circles it connects are also filled.

### Component 1
![image](https://github.com/GTBitsOfGood/brain-exercise-analytics/assets/57265280/28eaf706-fc65-4354-a655-f1499ed8785a)

A number of users over time graph shows up when you hover over the Total Users box. Take a look at the [Figma prototype](https://www.figma.com/proto/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=1598-13219&t=AdWDhUyfhv4p7Au0-0&scaling=min-zoom&page-id=1%3A6&starting-point-node-id=484%3A2828&show-proto-sidebar=1) 

### Component 2
![image](https://github.com/GTBitsOfGood/brain-exercise-analytics/assets/57265280/56b837e9-6790-4096-ab06-e7cd999dd99f)

An info popup shows up on clicking the info button beside the Active box. Take a look at the [Figma prototype](https://www.figma.com/proto/2ScQM6aE78OmEbB5pgdJKu/Brain-Exercise-Initiative-FALL23?type=design&node-id=1598-13219&t=AdWDhUyfhv4p7Au0-0&scaling=min-zoom&page-id=1%3A6&starting-point-node-id=484%3A2828&show-proto-sidebar=1) 

## Acceptance Criteria

- [x] Create the Streak component
- [x] Create the Overview component
- [x] Create the Overall Dashboard component

**Comment by thanasis457** [comment]
For the Streak  component we need more information than just days. We need the dates or the date range too to determine  the dates on the  x-axis.

It would also be really useful to use Redux to store the user information globally so we can access the user name, etc. globally in the app.
